;; -*- Mode:emacs-lisp; Syntax:ANSI-Common-LISP; Coding:us-ascii-unix; fill-column:158 -*-
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;; @file      mjr-dark-theme.el
;; @author    Mitch Richling <http://www.mitchr.me>
;; @brief     Mitch J Richling's Emacs Theme.@EOL
;; @std       Emacs Lisp
;; @see       
;; @copyright 
;;  @parblock
;;  Copyright (c) 2014-2015, Mitchell Jay Richling <http://www.mitchr.me> All rights reserved.
;;
;;  Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
;;
;;  1. Redistributions of source code must retain the above copyright notice, this list of conditions, and the following disclaimer.
;;
;;  2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions, and the following disclaimer in the documentation
;;     and/or other materials provided with the distribution.
;;
;;  3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software
;;     without specific prior written permission.
;;
;;  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;;  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;;  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
;;  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
;;  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
;;  DAMAGE.
;;  @endparblock
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(deftheme mjr-dark
  "Theme: Mitch Jay Richling DARK (mjr-dark)

   Loosely based on manoj-dark

   Goals:
     * Limited variable height text
     * High contrast faces on black background
     * Avoid subtle color variations
     * Easy on the eyes
     * Easy to edit")

(custom-theme-set-faces
 'mjr-dark
 '(default                                    ((t (:background "black" :foreground "WhiteSmoke"))))
 '(fixed-pitch                                ((t :inherit 'default)))
 
 '(font-lock-builtin-face                     ((t (:foreground "LightSteelBlue"))))
 '(font-lock-constant-face                    ((t (:foreground "LightSlateBlue"    :bold t))))
 '(font-lock-preprocessor-face                ((t (:foreground "CornFlowerBlue"                            :italic n :slant normal))))
 '(font-lock-keyword-face                     ((t (:foreground "cyan1"))))
 '(font-lock-type-face                        ((t (:foreground "SteelBlue1"))))
 '(font-lock-regexp-grouping-backslash        ((t (                                :bold t :weight bold))))
 '(font-lock-regexp-grouping-construct        ((t (                                :bold t :weight bold))))
 '(font-lock-variable-name-face               ((t (:foreground "Aquamarine"))))
 '(font-lock-function-name-face               ((t (:foreground "mediumspringgreen"         :weight bold))))
 '(font-lock-string-face                      ((t (:foreground "Salmon"))))
 '(font-lock-comment-face                     ((t (:foreground "Chocolate1"                                :italic n :slant normal))))
 '(font-lock-comment-delimiter-face           ((t (:foreground "Orange"))))
 '(font-lock-doc-face                         ((t (:foreground "LightCoral"                                :italic n :slant normal))))
 '(font-lock-doc-string-face                  ((t (:foreground "Plum"))))
 '(font-lock-warning-face                     ((t (:foreground "Pink"              :bold t :weight bold))))

 '(cperl-array-face                           ((t (:foreground "LawnGreen"   :background "Black" :bold t))))
 '(cperl-hash-face                            ((t (:foreground "SpringGreen" :background "Black" :bold t :italic t))))
 '(cperl-nonoverridable-face                  ((t (:foreground "chartreuse3"))))

 '(sh-heredoc                                 ((t (:foreground "Yellow3"    :bold t :weight bold))))
 '(sh-escaped-newline                         ((t (:foreground "black"      :background "Khaki"    :bold t :weight bold))))
 '(sh-quoted-exec                              ((t (:foreground "DarkOrchid1"    :bold t :weight bold))))


 '(link                                       ((t (:foreground "cyan1"  :underline t :bold t :weight bold))))
 '(link-visited                               ((t (:foreground "violet" :underline t :bold t :weight bold ))))

 '(gnus-button                                ((t (:bold t :weight bold :background "#191932" :box (:line-width 2 :style released-button)))))
 '(gnus-cite-attribution-face                 ((t (:italic t))))
 '(gnus-cite-face-1                           ((t (:foreground "CornflowerBlue"))))
 '(gnus-cite-face-2                           ((t (:foreground "PaleGreen"))))
 '(gnus-cite-face-3                           ((t (:foreground "LightGoldenrod"))))
 '(gnus-cite-face-4                           ((t (:foreground "LightPink"))))
 '(gnus-cite-face-5                           ((t (:foreground "turquoise"))))
 '(gnus-cite-face-6                           ((t (:foreground "khaki"))))
 '(gnus-cite-face-7                           ((t (:foreground "plum"))))
 '(gnus-cite-face-8                           ((t (:foreground "DeepSkyBlue1"))))
 '(gnus-cite-face-9                           ((t (:foreground "chartreuse1"))))
 '(gnus-cite-face-10                          ((t (:foreground "thistle1"))))
 '(gnus-cite-face-11                          ((t (:foreground "LightYellow1"))))
 '(gnus-emphasis-bold                         ((t (:bold t :weight bold))))
 '(gnus-emphasis-bold-italic                  ((t (:bold t :slant italic :weight bold))))
 '(gnus-emphasis-highlight-words              ((t (:background "black" :foreground "yellow"))))
 '(gnus-emphasis-italic                       ((t (:italic t :slant italic))))
 '(gnus-emphasis-strikethru                   ((t (:strike-through t))))
 '(gnus-emphasis-underline                    ((t (:underline t))))
 '(gnus-emphasis-underline-bold               ((t (:bold t :underline t :weight bold))))
 '(gnus-emphasis-underline-bold-italic        ((t (:italic t :bold t :underline t :slant italic :weight bold))))
 '(gnus-emphasis-underline-italic             ((t (:italic t :underline t :slant italic))))
 '(gnus-header-content                        ((t (:foreground "DarkKhaki" :italic n :slant normal))))
 '(gnus-header-content-face                   ((t (:foreground "DarkKhaki" :italic n :slant normal))))
 '(gnus-header-from                           ((t (:foreground "PaleGreen1"))))
 '(gnus-header-from-face                      ((t (:foreground "PaleGreen1"))))
 '(gnus-header-name                           ((t (:bold t :foreground "BlanchedAlmond" :weight bold))))
 '(gnus-header-name-face                      ((t (:bold t :foreground "BlanchedAlmond" :weight bold))))
 '(gnus-header-newsgroups                     ((t (:foreground "yellow" :italic n :slant normal))))
 '(gnus-header-newsgroups-face                ((t (:foreground "yellow" :italic n :slant normal))))
 '(gnus-header-subject                        ((t (:foreground "coral1"))))
 '(gnus-header-subject-face                   ((t (:foreground "coral1"))))
 '(gnus-signature                             ((t (:italic n :slant normal))))
 '(gnus-signature-face                        ((t (:italic n :slant normal))))
 '(gnus-splash                                ((t (:foreground "#cccccc"))))

 '(gnus-summary-cancelled                     ((t (:foreground "yellow"         :background "black"))))
 '(gnus-summary-cancelled-face                ((t (:foreground "yellow"         :background "black"))))
 '(gnus-summary-high-ancient                  ((t (:foreground "CornflowerBlue" :bold t :weight bold))))
 '(gnus-summary-high-ancient-face             ((t (:foreground "CornflowerBlue" :bold t :weight bold))))
 '(gnus-summary-normal-ancient                ((t (:foreground "SkyBlue"))))
 '(gnus-summary-normal-ancient-face           ((t (:foreground "SkyBlue"))))
 '(gnus-summary-low-ancient                   ((t (:foreground "LightSteelBlue" :italic n :slant normal))))
 '(gnus-summary-low-ancien-facet              ((t (:foreground "LightSteelBlue" :italic n :slant normal))))
 '(gnus-summary-high-read                     ((t (:foreground "grey60" :bold t :weight bold))))
 '(gnus-summary-high-read-face                ((t (:foreground "grey60" :bold t :weight bold))))
 '(gnus-summary-normal-read                   ((t (:foreground "grey50"))))
 '(gnus-summary-normal-read-face              ((t (:foreground "grey50"))))
 '(gnus-summary-low-read                      ((t (:foreground "LightSlateGray" :italic n :slant normal))))
 '(gnus-summary-low-read-face                 ((t (:foreground "LightSlateGray" :italic n :slant normal))))
 '(gnus-summary-high-ticked                   ((t (:foreground "RosyBrown" :bold t :weight bold))))
 '(gnus-summary-high-ticked-face              ((t (:foreground "RosyBrown" :bold t :weight bold))))
 '(gnus-summary-normal-ticked                 ((t (:foreground "LightSalmon"))))
 '(gnus-summary-normal-ticked-face            ((t (:foreground "LightSalmon"))))
 '(gnus-summary-low-ticked                    ((t (:foreground "pink" :italic n :slant normal))))
 '(gnus-summary-low-ticked-face               ((t (:foreground "pink" :italic n :slant normal))))
 '(gnus-summary-high-undownloaded             ((t (:foreground "ivory3" :bold t :weight bold))))
 '(gnus-summary-normal-undownloaded           ((t (:foreground "LightGray" :weight normal))))
 '(gnus-summary-low-undownloaded              ((t (:foreground "grey75" :italic n :slant normal :weight normal))))
 '(gnus-summary-high-unread                   ((t (:foreground "PaleGreen" :bold t :weight bold))))
 '(gnus-summary-high-unread-face              ((t (:foreground "PaleGreen" :bold t :weight bold))))
 '(gnus-summary-normal-unread                 ((t (:foreground "YellowGreen"))))
 '(gnus-summary-normal-unread-face            ((t (:foreground "YellowGreen"))))
 '(gnus-summary-low-unread                    ((t (:foreground "MediumSeaGreen" :italic n :slant normal))))
 '(gnus-summary-low-unread-face               ((t (:foreground "MediumSeaGreen" :italic n :slant normal))))
 '(gnus-summary-root-face                     ((t (:foreground "Red"                                  :bold t :weight bold))))
 '(gnus-summary-selected                      ((t (:foreground "LemonChiffon" :underline t))))
 '(gnus-summary-selected-face                 ((t (:foreground "LemonChiffon" :underline t))))

 '(gnus-user-agent-bad-face                   ((t (:foreground "red"    :background "black" :bold t :weight bold))))
 '(gnus-user-agent-good-face                  ((t (:foreground "green"  :background "black"))))
 '(gnus-user-agent-unknown-face               ((t (:foreground "orange" :background "black" :bold t :weight bold))))
 '(gnus-x-face                                ((t (:foreground "black"  :background "white"))))

 '(gnus-group-mail-1                          ((t (:foreground "#3BFF00" :bold t :weight normal))))
 '(gnus-group-mail-1-face                     ((t (:foreground "#3BFF00" :bold t :weight normal))))
 '(gnus-group-mail-2                          ((t (:foreground "#5EFF00" :bold t :weight normal))))
 '(gnus-group-mail-2-face                     ((t (:foreground "#5EFF00" :bold t :weight normal))))
 '(gnus-group-mail-3                          ((t (:foreground "#80FF00" :bold t :weight normal))))
 '(gnus-group-mail-3-face                     ((t (:foreground "#A1FF00" :bold t :weight normal))))

 '(gnus-group-mail-1-empty                    ((t (:foreground "#249900"))))
 '(gnus-group-mail-1-empty-face               ((t (:foreground "#249900"))))
 '(gnus-group-mail-2-empty                    ((t (:foreground "#389900"))))
 '(gnus-group-mail-2-empty-face               ((t (:foreground "#389900"))))
 '(gnus-group-mail-3-empty                    ((t (:foreground "#4D9900"))))
 '(gnus-group-mail-3-empty-face               ((t (:foreground "#4D9900"))))

 '(gnus-group-mail-low                        ((t (:foreground "aquamarine2" :bold t :weight bold))))
 '(gnus-group-mail-low-face                   ((t (:foreground "aquamarine2" :bold t :weight bold))))
 '(gnus-group-mail-low-empty                  ((t (:foreground "aquamarine2"))))
 '(gnus-group-mail-low-empty-face             ((t (:foreground "aquamarine2"))))

 '(gnus-group-news-1                          ((t (:bold t :foreground "#8480FF" :weight bold))))
 '(gnus-group-news-1-face                     ((t (:bold t :foreground "#8480FF" :weight bold))))
 '(gnus-group-news-2                          ((t (:bold t :foreground "#8088FF" :weight bold))))
 '(gnus-group-news-2-face                     ((t (:bold t :foreground "#8088FF" :weight bold))))
 '(gnus-group-news-3                          ((t (:bold t :foreground "#8095FF" :weight bold))))
 '(gnus-group-news-3-face                     ((t (:bold t :foreground "#8095FF" :weight bold))))
 '(gnus-group-news-4                          ((t (:bold t :foreground "#80A1FF" :weight bold))))
 '(gnus-group-news-4-face                     ((t (:bold t :foreground "#80A1FF" :weight bold))))
 '(gnus-group-news-5                          ((t (:bold t :foreground "#80AEFF" :weight bold))))
 '(gnus-group-news-5-face                     ((t (:bold t :foreground "#80AEFF" :weight bold))))
 '(gnus-group-news-6                          ((t (:bold t :foreground "#80BBFF" :weight bold))))
 '(gnus-group-news-6-face                     ((t (:bold t :foreground "#80BBFF" :weight bold))))

 '(gnus-group-news-1-empty                    ((t (:foreground "#524DFF"))))
 '(gnus-group-news-1-empty-face               ((t (:foreground "#524DFF"))))
 '(gnus-group-news-2-empty                    ((t (:foreground "#4D58FF"))))
 '(gnus-group-news-2-empty-face               ((t (:foreground "#4D58FF"))))
 '(gnus-group-news-3-empty                    ((t (:foreground "#4D6AFF"))))
 '(gnus-group-news-3-empty-face               ((t (:foreground "#4D6AFF"))))
 '(gnus-group-news-4-empty                    ((t (:foreground "#4D7CFF"))))
 '(gnus-group-news-4-empty-face               ((t (:foreground "#4D7CFF"))))
 '(gnus-group-news-5-empty                    ((t (:foreground "#4D8EFF"))))
 '(gnus-group-news-5-empty-face               ((t (:foreground "#4D8EFF"))))
 '(gnus-group-news-6-empty                    ((t (:foreground "#4DA0FF"))))
 '(gnus-group-news-6-empty-face               ((t (:foreground "#4DA0FF"))))

 '(gnus-group-news-low                        ((t (:foreground "DarkTurquoise" :bold t :weight bold))))
 '(gnus-group-news-low-face                   ((t (:foreground "DarkTurquoise" :bold t :weight bold))))
 '(gnus-group-news-low-empty                  ((t (:foreground "DarkTurquoise"))))
 '(gnus-group-news-low-empty-face             ((t (:foreground "DarkTurquoise"))))

 '(message-cited-text                         ((t (:foreground "red3"))))
 '(message-header-cc                          ((t (:foreground "chartreuse1"      :bold t :weight bold))))
 '(message-header-cc-face                     ((t (:foreground "chartreuse1"      :bold t :weight bold))))
 '(message-header-name                        ((t (:foreground "green"))))
 '(message-header-name-face                   ((t (:foreground "green"))))
 '(message-header-newsgroups                  ((t (:foreground "papaya whip"      :bold t :weight bold :italic n :slant normal))))
 '(message-header-newsgroups-face             ((t (:foreground "papaya whip"      :bold t :weight bold :italic n :slant normal))))
 '(message-header-other                       ((t (:foreground "ivory"))))
 '(message-header-other-face                  ((t (:foreground "ivory"))))
 '(message-header-subject                     ((t (:foreground "OliveDrab1"))))
 '(message-header-subject-face                ((t (:foreground "OliveDrab1"))))
 '(message-header-to                          ((t (:foreground "floral white"     :bold t :weight bold))))
 '(message-header-to-face                     ((t (:foreground "floral white"     :bold t :weight bold))))
 '(message-header-xheader                     ((t (:foreground "DeepSkyBlue1"))))
 '(message-header-xheader-face                ((t (:foreground "DeepSkyBlue1"))))
 '(message-mml                                ((t (:foreground "MediumSpringGreen"))))
 '(message-mml-face                           ((t (:foreground "MediumSpringGreen"))))
 '(message-separator                          ((t (:foreground "LightSkyBlue1"))))
 '(message-separator-face                     ((t (:foreground "LightSkyBlue1"))))
 '(message-url                                ((t (:foreground "blue"             :bold t :weight bold))))

 '(bg:erc-color-face0                         ((t (                       :background "saddle brown"))))
 '(bg:erc-color-face1                         ((t (                       :background "black"))))
 '(bg:erc-color-face10                        ((t (                       :background "DodgerBlue4"))))
 '(bg:erc-color-face11                        ((t (                       :background "cyan4"))))
 '(bg:erc-color-face12                        ((t (                       :background "blue"))))
 '(bg:erc-color-face13                        ((t (                       :background "deeppink"))))
 '(bg:erc-color-face14                        ((t (                       :background "gray50"))))
 '(bg:erc-color-face15                        ((t (                       :background "grey15"))))
 '(bg:erc-color-face2                         ((t (                       :background "blue4"))))
 '(bg:erc-color-face3                         ((t (                       :background "green4"))))
 '(bg:erc-color-face4                         ((t (                       :background "red"))))
 '(bg:erc-color-face5                         ((t (                       :background "brown"))))
 '(bg:erc-color-face6                         ((t (                       :background "purple"))))
 '(bg:erc-color-face7                         ((t (                       :background "orange"))))
 '(bg:erc-color-face8                         ((t (                       :background "yellow4"))))
 '(bg:erc-color-face9                         ((t (                       :background "green"))))
 '(erc-action-face                            ((t (:foreground "turquoise1"    :bold t :weight bold ))))
 '(erc-bold-face                              ((t (                            :bold t :weight bold ))))
 '(erc-button                                 ((t (:foreground "RoyalBlue1"    :bold t :weight bold :box (:line-width 2 :style released-button)))))
 '(erc-button-face                            ((t (:foreground "RoyalBlue1"    :bold t :weight bold :box (:line-width 2 :style released-button)))))
 '(erc-command-indicator-face                 ((t (                            :bold t :weight bold))))
 '(erc-current-nick-face                      ((t (:foreground "DarkTurquoise" :bold t :weight bold))))
 '(erc-dangerous-host-face                    ((t (:foreground "red"))))
 '(erc-direct-msg-face                        ((t (:foreground "sandybrown"))))
 '(erc-error-face                             ((t (:foreground "red"))))
 '(erc-fool-face                              ((t (:foreground "dim gray"))))
 '(erc-header-line                            ((t (:foreground "ConFlowerBlue" :background "grey95" ))))
 '(erc-input-face                             ((t (:foreground "brown"))))
 '(erc-inverse-face                           ((t (:foreground "White" :background "Black" ))))
 '(erc-keyword-face                           ((t (:foreground "pale green"                    :bold t :weight bold))))
 '(erc-my-nick-face                           ((t (:foreground "brown"                         :bold t :weight bold))))
 '(erc-nick-default-face                      ((t (:foreground "DodgerBlue1"                   :bold t :weight bold))))
 '(erc-button-nickname-face                   ((t (:foreground "black" :background "lightgrey" :bold t :weight bold :box (:line-width 2 :style released-button) ))))
 '(erc-nick-msg-face                          ((t (:foreground "IndianRed"                     :bold t :weight bold))))
 '(erc-notice-face                            ((t (:foreground "SlateBlue"                     :bold t :weight bold))))
 '(erc-pal-face                               ((t (:foreground "Magenta"                       :bold t :weight bold))))
 '(erc-prompt-face                            ((t (:foreground "lightBlue2" :background "Navy" :bold t :weight bold))))
 '(erc-timestamp-face                         ((t (:foreground "SeaGreen1"                     :bold t :weight bold))))
 '(erc-underline-face                         ((t (:underline t))))
 '(fg:erc-color-face0                         ((t (:foreground "BlanchedAlmond"))))
 '(fg:erc-color-face1                         ((t (:foreground "beige"))))
 '(fg:erc-color-face10                        ((t (:foreground "pale goldenrod"))))
 '(fg:erc-color-face11                        ((t (:foreground "cyan"))))
 '(fg:erc-color-face12                        ((t (:foreground "lightblue1"))))
 '(fg:erc-color-face13                        ((t (:foreground "deeppink"))))
 '(fg:erc-color-face14                        ((t (:foreground "gray50"))))
 '(fg:erc-color-face15                        ((t (:foreground "gray90"))))
 '(fg:erc-color-face2                         ((t (:foreground "blue4"))))
 '(fg:erc-color-face3                         ((t (:foreground "green4"))))
 '(fg:erc-color-face4                         ((t (:foreground "red"))))
 '(fg:erc-color-face5                         ((t (:foreground "brown"))))
 '(fg:erc-color-face6                         ((t (:foreground "purple"))))
 '(fg:erc-color-face7                         ((t (:foreground "orange"))))
 '(fg:erc-color-face8                         ((t (:foreground "yellow"))))
 '(fg:erc-color-face9                         ((t (:foreground "green"))))

 '(org-agenda-date                            ((t (:foreground "LightSkyBlue"))))
 '(org-agenda-date-weekend                    ((t (:foreground "LightSkyBlue" :bold t :weight bold))))
 '(org-agenda-restriction-lock                ((t (:background "skyblue4"))))
 '(org-agenda-structure                       ((t (:foreground "LightSkyBlue"))))
 '(org-archived                               ((t (:foreground "grey70"))))
 '(org-block-begin-line                       ((t (:background "#151f3f" :inherit 'org-meta-line))))
 '(org-block-end-line                         ((t (:background "#151f3f" :inherit 'org-meta-line))))
 '(org-document-info-keyword                  ((t (                      :inherit 'org-meta-line))))
 '(org-code                                   ((t (:foreground "grey70"))))
 '(org-column                                 ((t (:background "grey30" :slant normal :weight normal))))
 '(org-column-title                           ((t (:background "grey30" :bold t :weight bold :underline t))))
 '(org-date                                   ((t (:foreground "Cyan" :underline t))))
 '(org-done                                   ((t (:foreground "PaleGreen" :bold t :weight bold))))
 '(org-drawer                                 ((t (:foreground "LightSkyBlue"))))
 '(org-ellipsis                               ((t (:foreground "LightGoldenrod" :underline t))))
 '(org-formula                                ((t (:foreground "chocolate1"))))
 '(org-headline-done                          ((t (:foreground "LightSalmon"))))
 '(org-hide                                   ((t (:foreground "black"))))
 '(org-latex-and-export-specials              ((t (:foreground "burlywood"))))
 '(org-level-1                                ((t (:foreground "LightSkyBlue"   :bold 't :weight bold))))
 '(org-level-2                                ((t (:foreground "LightGoldenrod" :bold 't :weight bold))))
 '(org-level-3                                ((t (:foreground "Cyan1"          :bold 't :weight bold))))
 '(org-level-4                                ((t (:foreground "chocolate1"     :bold 't :weight bold))))
 '(org-level-5                                ((t (:foreground "PaleGreen"      :bold 't :weight bold))))
 '(org-level-6                                ((t (:foreground "Aquamarine"     :bold 't :weight bold))))
 '(org-level-7                                ((t (:foreground "LightSteelBlue" :bold 't :weight bold))))
 '(org-level-8                                ((t (:foreground "LightSalmon"    :bold 't :weight bold))))
 '(org-link                                   ((t (:foreground "Cyan"      :underline t))))
 '(org-mode-line-clock                        ((t (:foreground "DarkGreen" :underline t))))
 '(org-scheduled-previously                   ((t (:foreground "chocolate1"))))
 '(org-scheduled-today                        ((t (:foreground "PaleGreen"))))
 '(org-sexp-date                              ((t (:foreground "Cyan"))))
 '(org-special-keyword                        ((t (:foreground "LightSalmon"))))
 '(org-table                                  ((t (:foreground "LightSkyBlue"))))
 '(org-tag                                    ((t (                             :bold t :weight bold))))
 '(org-target                                 ((t (:underline t))))
 '(org-time-grid                              ((t (:foreground "LightGoldenrod"))))
 '(org-todo                                   ((t (:foreground "Pink"           :bold t :weight bold))))
 '(org-upcoming-deadline                      ((t (:foreground "chocolate1"))))
 '(org-verbatim                               ((t (:foreground "grey70" :underline t))))
 '(org-warning                                ((t (:foreground "Pink"           :bold t :weight bold ))))

 '(outline-1                                  ((t (:foreground "LightSkyBlue"   :bold t :weight bold))))
 '(outline-2                                  ((t (:foreground "LightGoldenrod" :bold t :weight bold))))
 '(outline-3                                  ((t (:foreground "Cyan1"          :bold t :weight bold))))
 '(outline-4                                  ((t (:foreground "chocolate1"     :bold t :weight bold))))
 '(outline-5                                  ((t (:foreground "PaleGreen"      :bold t :weight bold))))
 '(outline-6                                  ((t (:foreground "Aquamarine"     :bold t :weight bold))))
 '(outline-7                                  ((t (:foreground "LightSteelBlue" :bold t :weight bold))))
 '(outline-8                                  ((t (:foreground "LightSalmon"    :bold t :weight bold))))

 '(CUA-global-mark-face                       ((t (:background "cyan"    :foreground "black"))))
 '(CUA-rectangle-face                         ((t (:background "maroon"  :foreground "white"))))
 '(CUA-rectangle-noselect-face                ((t (:background "dimgray" :foreground "white"))))

 '(align-highlight-nochange-face              ((t (:background "SkyBlue4"))))

 '(antlr-font-lock-keyword-face               ((t (:foreground "SteelBlue")))) ;%
 '(antlr-font-lock-literal-face               ((t (:foreground "PaleVioletRed"))))
 '(antlr-font-lock-ruledef-face               ((t (:foreground "DarkGreen"))))
 '(antlr-font-lock-ruleref-face               ((t (:foreground "SteelBlue"))))
 '(antlr-font-lock-tokendef-face              ((t (:foreground "khaki"))))
 '(antlr-font-lock-tokenref-face              ((t (:foreground "LightSteelBlue4"))))

 '(bbdb-company                               ((t (:italic n :slant normal :foreground "indian red"))))
 '(bbdb-field-name                            ((t (:bold t :weight bold :foreground "steel blue"))))
 '(bbdb-field-value                           ((t (:foreground "AntiqueWhite2"))))
 '(bbdb-name                                  ((t (:underline t :foreground "cadet blue"))))

 '(bold                                       ((t (:bold t :weight bold))))
 '(bold-italic                                ((t (:bold t :italic t :slant italic :weight bold))))
 '(border                                     ((t (:foreground "black" :background "gold"))))
 '(buffer-menu-buffer                         ((t (:foreground "Gold" :bold t :weight bold))))
 '(button                                     ((t (:underline nil :foreground "ivory" :background "royal blue" :weight bold
                                                              :box (:line-width 2 :color "cornflower blue" :style released-button)))))

 '(change-log-acknowledgement-face            ((t (:foreground "AntiqueWhite3" :italic t :slant oblique ))))
 '(change-log-conditionals-face               ((t (:foreground "Aquamarine"))))
 '(change-log-date-face                       ((t (:foreground "BurlyWood"     :italic t :slant oblique))))
 '(change-log-email-face                      ((t (:foreground "Aquamarine"))))
 '(change-log-file-face                       ((t (:foreground "LightSkyBlue"  :bold t :weight bold ))))
 '(change-log-function-face                   ((t (:foreground "Aquamarine"))))
 '(change-log-list-face                       ((t (:foreground "LightSkyBlue"))))
 '(change-log-name-face                       ((t (:foreground "Gold"          :bold t :weight bold ))))

 '(comint-highlight-input                     ((t (                    :bold t :weight bold :inherit 'default))))
 '(comint-highlight-prompt                    ((t (:foreground "Green" :bold t :weight bold))))


 '(slime-repl-prompt-face                     ((t (:inherit 'comint-highlight-prompt))))
 '(slime-repl-input-face                      ((t (:inherit 'comint-highlight-input))))
 '(slime-repl-output-face                     ((t (:inherit 'font-lock-string-face))))
 '(slime-repl-result-face                     ((t (:foreground "CadetBlue3"))))
 
 '(compilation-column-number                  ((t (:foreground "PaleGreen"))))
 '(compilation-error                          ((t (:foreground "Brown1" :bold t :weight bold ))))
 '(compilation-info                           ((t (:foreground "LightPink1" :bold t :weight bold))))
 '(compilation-line-number                    ((t (:foreground "LightGoldenrod"))))
 '(compilation-message-face                   ((t (:underline t))))
 '(compilation-warning                        ((t (:foreground "Orange" :bold t :weight bold))))
 '(compilation-warning-face                   ((t (:foreground "Orange" :bold t :weight bold))))
 '(completions-common-part                    ((t (:foreground "WhiteSmoke" :background "black" :width normal :weight normal :slant normal))))
 '(completions-first-difference               ((t (:bold t :weight bold))))

 '(css-selector                               ((t (:foreground "LightSteelBlue"))))
 '(css-property                               ((t (:foreground "light sea green"))))

 '(cursor                                     ((t (:background "red"))))

 '(custom-button-face                         ((t (:background "lightgrey" :foreground "black" :box '(:line-width 2 :style released-button)))))
 '(custom-button-pressed-face                 ((t (:background "lightgrey" :foreground "black" :box '(:line-width 2 :style pressed-button)))))
 '(custom-changed-face                        ((t (:foreground "wheat" :background "blue"))))
 '(custom-comment-face                        ((t (:background "dim gray"))))
 '(custom-comment-tag-face                    ((t (:foreground "gray80"))))
 '(custom-face-tag-face                       ((t (:bold t :weight bold))))
 '(custom-group-tag-face                      ((t (:bold t :foreground "light blue" :weight bold))))
 '(custom-group-tag-face-1                    ((t (:bold t :foreground "pink" :weight bold))))
 '(custom-invalid-face                        ((t (:background "red" :foreground "yellow"))))
 '(custom-modified-face                       ((t (:background "blue" :foreground "white"))))
 '(custom-rogue-face                          ((t (:background "black" :foreground "pink"))))
 '(custom-saved-face                          ((t (:underline t))))
 '(custom-set-face                            ((t (:background "white" :foreground "blue"))))
 '(custom-state-face                          ((t (:foreground "lime green"))))
 '(custom-variable-button-face                ((t (:bold t :underline t :weight bold :background "lightgrey" :foreground "black" :box '(:line-width 2 :style released-button)))))
 '(custom-variable-tag-face                   ((t (:bold t :foreground "light blue" :weight bold))))

 '(calendar-today-face                        ((t (:underline t :bold t :foreground "cornsilk"))))
 '(calendar-weekday-header                    ((t (:underline t :bold t :foreground "Purple"))))
 '(calendar-weekend-header                    ((t (:underline t :bold t :foreground "Red"))))
 '(calendar-month-header                      ((t (:underline t :bold t :foreground "limegreen"))))
 
 '(diary                                      ((t (:foreground "IndianRed"))))
 '(diary-anniversary                          ((t (:foreground "Cyan1"))))
 '(diary-button                               ((t (:background "lightgrey" :foreground "black"  :box (:line-width 2 :style released-button)))))
 '(diary-face                                 ((t (:foreground "IndianRed"))))
 '(diary-time                                 ((t (:foreground "LightGoldenrod"))))

 '(diff-added                                 ((t (:foreground "Green"))))
 '(diff-added-face                            ((t (:foreground "Green"))))
 '(diff-changed-face                          ((t (:foreground "Khaki"))))
 '(diff-context-face                          ((t (:foreground "grey70"))))
 '(diff-file-header                           ((t (:foreground "ivory1" :background "grey20"     :bold t :weight bold))))
 '(diff-file-header-face                      ((t (:foreground "ivory1" :background "grey20"     :bold t :weight bold))))
 '(diff-function-face                         ((t (:foreground "SpringGreen1"))))
 '(diff-header-face                           ((t (:background "SlateBlue4"))))
 '(diff-hunk-header                           ((t (:background "DodgerBlue4"                                            :slant italic))))
 '(diff-hunk-header-face                      ((t (:background "DodgerBlue4"                                            :slant italic))))
 '(diff-index-face                            ((t (:foreground "linen"  :background "SteelBlue4" :bold t :weight bold))))
 '(diff-nonexistent                           ((t (:foreground "Wheat1" :background "Black"      :bold t :weight bold))))
 '(diff-nonexistent-face                      ((t (:foreground "Wheat1" :background "Black"      :bold t :weight bold))))
 '(diff-removed                               ((t (:foreground "salmon1"))))
 '(diff-removed-face                          ((t (:foreground "salmon1"))))
 '(diff-refine-change-face                    ((t (:background "MidnightBlue"))))
 '(diff-refine-change                         ((t (:background "MidnightBlue"))))

 '(ediff-current-diff-face-A                  ((t (:foreground "firebrick"  :background "pale green"))))
 '(ediff-current-diff-face-Ancestor           ((t (:foreground "Black"      :background "VioletRed"))))
 '(ediff-current-diff-face-B                  ((t (:foreground "DarkOrchid" :background "Yellow"))))
 '(ediff-current-diff-face-C                  ((t (:foreground "Navy"       :background "Pink"))))
 '(ediff-even-diff-face-A                     ((t (:foreground "Black"      :background "light grey"))))
 '(ediff-even-diff-face-Ancestor              ((t (:foreground "White"      :background "Grey"))))
 '(ediff-even-diff-face-B                     ((t (:foreground "White"      :background "Grey"))))
 '(ediff-even-diff-face-C                     ((t (:foreground "Black"      :background "light grey"))))
 '(ediff-fine-diff-face-A                     ((t (:foreground "Navy"       :background "sky blue"))))
 '(ediff-fine-diff-face-Ancestor              ((t (:foreground "Black"      :background "Green"))))
 '(ediff-fine-diff-face-B                     ((t (:foreground "Black"      :background "cyan"))))
 '(ediff-fine-diff-face-C                     ((t (:foreground "Black"      :background "Turquoise"))))
 '(ediff-odd-diff-face-A                      ((t (:foreground "White"      :background "Grey"))))
 '(ediff-odd-diff-face-Ancestor               ((t (:foreground "Black"      :background "light grey"))))
 '(ediff-odd-diff-face-B                      ((t (:foreground "Black"      :background "light grey"))))
 '(ediff-odd-diff-face-C                      ((t (:foreground "White"      :background "Grey"))))

 '(eieio-custom-slot-tag-face                 ((t (:foreground "light blue"))))
 '(eldoc-highlight-function-argument          ((t (:bold t :weight bold))))

 '(epa-field-body                             ((t (:italic t :foreground "turquoise" :slant italic))))
 '(epa-field-name                             ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
 '(epa-mark                                   ((t (:bold t :foreground "orange" :weight bold))))
 '(epa-string                                 ((t (:foreground "lightyellow"))))
 '(epa-validity-disabled                      ((t (:italic t :slant italic))))
 '(epa-validity-high                          ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
 '(epa-validity-low                           ((t (:italic t :slant italic))))
 '(epa-validity-medium                        ((t (:italic t :foreground "PaleTurquoise" :slant italic))))

 '(escape-glyph                               ((t (:foreground "cyan"))))

 '(eshell-ls-archive-face                     ((t (                                                 :inherit 'default))))
 '(eshell-ls-backup-face                      ((t (:foreground "IndianRed"))))
 '(eshell-ls-unreadable-face                  ((t (                                                 :inherit 'default))))
 '(eshell-ls-clutter-face                     ((t (                                                 :inherit 'default))))
 '(eshell-ls-executable-face                  ((t (:foreground "green"))))
 '(eshell-ls-missing-face                     ((t (                      :background "red"))))
 '(eshell-ls-picture-face                     ((t (                                                 :inherit 'default))))
 '(eshell-ls-product-face                     ((t (                                                 :inherit 'default))))
 '(eshell-ls-readonly-face                    ((t (                                                 :inherit 'default))))
;; '(eshell-prompt-face                         ((t (                                                 :inherit 'comint-highlight-prompt))))

 '(eshell-prompt-face                         ((t (:foreground "Green" :bold t :weight bold))))

 '(eshell-test-failed-face                    ((t (:foreground "OrangeRed"            :bold t :weight bold))))
 '(eshell-test-ok-face                        ((t (:foreground "Green"                :bold t :weight bold))))
 '(eshell-ls-directory-face                   ((t (:foreground "Blue3"                :bold t :weight bold))))
 '(eshell-ls-special-face                     ((t (:foreground "Gold"))))
 '(eshell-ls-symlink-face                     ((t (:foreground "Cyan"                 :bold t :weight bold))))

 '(excerpt                                    ((t (:italic t))))
 '(file-name-shadow                           ((t (:foreground "grey70"))))
 '(fixed                                      ((t (:bold t))))
 
 '(flyspell-duplicate-face                    ((t (:foreground "IndianRed" :bold t :underline t))))
 '(flyspell-incorrect-face                    ((t (:foreground "Pink" :bold t :underline t))))

 '(fringe                                     ((t (:background "grey30" :foreground "Wheat"))))
 '(header-line                                ((t (:box (:line-width -1 :color "grey20" :style released-button) :background "grey20" :foreground "grey90"))))
 '(help-argument-name                         ((t (:italic t :slant italic))))
 '(highlight                                  ((t (:foreground "Old Lace" :background "gray20"        ))))
 '(hl-line                                    ((t (:foreground "Old Lace" :background "grey20"        ))))
 '(gnus-mouse-face                            ((t (:foreground "blue"     :background "darkseagreen2" ))))
 '(erc-button-mouse-face                      ((t (:foreground "blue"     :background "darkseagreen2" ))))
 '(align-highlight-change-face                ((t (:foreground "blue"     :background "darkseagreen2" ))))
 '(goto-address-url-mouse-face                ((t (:foreground "blue"     :background "darkseagreen2" ))))

 '(ispell-highlight-face                      ((t (:foreground "blue"     :background "darkseagreen2" ))))

 '(widget-mouse-face                          ((t (:foreground "blue"     :background "darkseagreen2" ))))

 '(highlight-beyond-fill-column-face          ((t (:underline t))))
 '(highlight-changes                          ((t (:foreground nil :background "#382f2f"))))
 '(highlight-changes-delete                   ((t (:foreground nil :background "#916868"))))

 '(holiday                                    ((t (:background "chocolate4"))))
 '(holiday-face                               ((t (:background "chocolate4"))))

 '(ibuffer-dired-buffer-face                  ((t (:foreground "mediumspringgreen" :weight bold))))
 '(ibuffer-help-buffer-face                   ((t (:italic t :slant oblique :foreground "chocolate1"))))
 '(ibuffer-hidden-buffer-face                 ((t (:bold t :foreground "Pink" :weight bold))))
 '(ibuffer-occur-match-face                   ((t (:bold t :foreground "Pink" :weight bold))))
 '(ibuffer-read-only-buffer-face              ((t (:foreground "SteelBlue1"))))
 '(ibuffer-special-buffer-face                ((t (:foreground "SteelBlue1"))))
 
 '(ido-first-match                            ((t (:foreground "OliveDrab1" ))))
 '(ido-incomplete-regexp                      ((t (:foreground "Pink" :bold t :weight bold ))))
 '(ido-indicator                              ((t (:foreground "yellow1" :background "red1" :width condensed))))
 '(ido-only-match                             ((t (:foreground "Green" :bold t :weight bold))))
 '(ido-subdir                                 ((t (:foreground "red1"))))

 '(info-header-node                           ((t (:foreground "LightSkyBlue"    :bold t :weight bold))))
 '(info-title-1                               ((t (:foreground "LightGoldenrod"  :bold t :weight bold))))
 '(info-title-2                               ((t (:foreground "Cyan1"           :bold t :weight bold))))
 '(info-title-3                               ((t (:foreground "chocolate1"      :bold t :weight bold))))
 '(info-title-4                               ((t (:foreground "PaleGreen"       :bold t :weight bold))))
 '(info-menu-star                             ((t (:foreground "Red"             :bold t :weight bold))))
 '(info-menu-header                           ((t (:foreground "Red"             :bold t :weight bold))))
 '(info-node                                  ((t (:foreground "yellow"          :bold t              :italic t))))

 '(isearch                                    ((t (:foreground "brown4" :background "palevioletred2"))))
 '(isearch-fail                               ((t (                     :background "red4"))))
 '(isearch-lazy-highlight-face                ((t (                     :background "paleturquoise4"))))
 '(isearch-secondary                          ((t (:foreground "red3"))))

 '(italic                                     ((t (:italic t))))

 '(js2-builtin-face                           ((t (:foreground "sandy brown"))))
 '(js2-comment-face                           ((t (:foreground "dark orchid"))))
 '(js2-constant-face                          ((t (:foreground "pale violet red"))))
 '(js2-error-face                             ((t (:foreground "green"           :background "indian red" :bold t))))
 '(js2-function-name-face                     ((t (:foreground "cadet blue"))))
 '(js2-function-param-face                    ((t (:foreground "IndianRed1"))))
 '(js2-instance-member-face                   ((t (:foreground "IndianRed1"))))
 '(js2-jsdoc-tag-face                         ((t (:foreground "medium orchid"))))
 '(js2-jsdoc-type-face                        ((t (:foreground "medium orchid"))))
 '(js2-jsdoc-value-face                       ((t (:foreground "medium orchid"))))
 '(js2-keyword-face                           ((t (:foreground "steel blue"))))
 '(js2-private-function-call-face             ((t (:foreground "cadet blue"))))
 '(js2-private-member-face                    ((t (:foreground "IndianRed1"))))
 '(js2-regexp-face                            ((t (:foreground "khaki"))))
 '(js2-string-face                            ((t (:foreground "lemon chiffon"))))
 '(js2-type-face                              ((t (:foreground "medium sea green"))))
 '(js2-variable-name-face                     ((t (:foreground "IndianRed1"))))
 '(js2-warning-face                           ((t (:foreground "green"           :background "indian red"))))

 '(lazy-highlight                             ((t (:background "paleturquoise4"))))

 '(makefile-space                             ((t (:background "hotpink"))))

 '(match                                      ((t (:background "RoyalBlue3"))))
 '(minibuffer-prompt                          ((t (:foreground "cyan"))))

 '(mode-line                                  ((t (:foreground "Blue4"  :background "grey80" ))))
 '(mode-line-inactive                         ((t (:foreground "grey80" :background "grey20"))))
 '(mode-line-buffer-id                        ((t (:foreground "Red1" :bold t :weight bold :width condensed))))
 '(mode-line-emphasis                         ((t (:bold t :weight bold))))
 '(mode-line-highlight                        ((t (:foreground  "Red4"))))

 '(display-time-mail-face                     ((t (:inherit 'mode-line-emphasis :foreground "Red"))))
 
 '(mouse                                      ((t (:background "OrangeRed"))))

 '(next-error                                 ((t (:background "blue3"))))
 '(nobreak-space                              ((t (:foreground "cyan" :underline t))))

 '(paren-blink-off                            ((t (:foreground "black"))))
 '(paren-mismatch-face                        ((t (:bold t :background "white" :foreground "red"))))
 '(paren-no-match-face                        ((t (:bold t :background "white" :foreground "red"))))

 '(query-replace                              ((t (:foreground "brown4" :background "palevioletred2"))))
 '(region                                     ((t (:background "blue3"))))
 '(scroll-bar                                 ((t (:background "grey75" :foreground "WhiteSmoke"))))
 '(secondary-selection                        ((t (:background "SkyBlue4"))))

 '(semantic-dirty-token-face                  ((t (:background "lightyellow"))))
 '(semantic-highlight-edits-face              ((t (:background "gray20"))))
 '(semantic-unmatched-syntax-face             ((t (:underline "red"))))

 '(senator-intangible-face                    ((t (:foreground "gray75"))))
 '(senator-momentary-highlight-face           ((t (:background "gray30"))))
 '(senator-read-only-face                     ((t (:background "#664444"))))

 '(shadow                                     ((t (:foreground "grey70"))))

 '(show-paren-match                           ((t (:background "steelblue3"))))
 '(show-paren-match-face                      ((t (:background "steelblue3"))))
 '(show-paren-mismatch                        ((t (:background "purple" :foreground "white"))))

 '(smerge-base                                ((t (:foreground "orange"))))
 '(smerge-markers                             ((t (:background "grey30"))))
 '(smerge-mine                                ((t (:foreground "cyan"))))
 '(smerge-other                               ((t (:foreground "lightgreen"))))
 '(smerge-refined-change                      ((t (:background "blue4"))))

 '(speedbar-button-face                       ((t (:foreground "green3"))))
 '(speedbar-directory-face                    ((t (:foreground "light blue"))))
 '(speedbar-file-face                         ((t (:foreground "cyan"))))
 '(speedbar-highlight-face                    ((t (:background "sea green"))))
 '(speedbar-selected-face                     ((t (:foreground "red" :underline t))))
 '(speedbar-separator-face                    ((t (:background "blue" :foreground "white" :overline "gray"))))
 '(speedbar-tag-face                          ((t (:foreground "yellow"))))

 '(table-cell                                 ((t (:foreground "gray90" :background "blue1"))))

 '(tool-bar                                   ((t (:foreground "black" :background "grey75" :box (:line-width 1 :style released-button)))))
 '(tooltip                                    ((t (:foreground "black" :background "lightyellow" ))))
 '(trailing-whitespace                        ((t (:background "red1"))))
 '(underline                                  ((t (:underline t))))
 '(vcursor                                    ((t (:foreground "blue"  :background "cyan" :underline t))))
 '(vertical-border                            ((t (:background "dim gray"))))

 '(vm-highlight-url-face                      ((t (:bold t :italic t :slant italic :weight bold))))
 '(vm-highlighted-header-face                 ((t (:bold t :weight bold))))
 '(vm-mime-button-face                        ((t (:foreground "black" :background "grey75" :box (:line-width 2 :style released-button)))))
 '(vm-summary-highlight-face                  ((t (:bold t :weight bold))))
 '(vm-xface                                   ((t (:foreground "black" :background "white"))))

 '(which-func                                 ((t (:foreground "Blue1"))))

 '(widget                                     ((t (:foreground "black" :background "Gray80"))))
 '(widget-button                              ((t (:bold t :weight bold :box (:line-width 2 :style released-button)))))
 '(widget-button-face                         ((t (:bold t :weight bold :box (:line-width 2 :style released-button)))))
 '(widget-button-pressed                      ((t (:foreground "red1" :background "lightgrey" :box (:line-width 2 :style pressed-button)))))
 '(widget-button-pressed-face                 ((t (:foreground "red1" :background "lightgrey" :box (:line-width 2 :style pressed-button)))))
 '(widget-documentation                       ((t (:foreground "lime green"))))
 '(widget-documentation-face                  ((t (:foreground "lime green"))))
 '(widget-field                               ((t (:background "dim gray"))))
 '(widget-field-face                          ((t (:background "dim gray"))))
 '(widget-inactive                            ((t (:foreground "grey70"))))
 '(widget-inactive-face                       ((t (:foreground "grey70"))))
 '(widget-single-line-field                   ((t (:background "dim gray"))))
 '(widget-single-line-field-face              ((t (:background "dim gray"))))

 '(woman-bold-face                            ((t (:foreground "Gold"      :bold t :weight bold))))
 '(woman-italic-face                          ((t (:foreground "LightBlue" :underline t))))
 '(woman-unknown-face                         ((t (:foreground "Black"     :background "Pink"))))

 '(Man-overstrike                             ((t (:foreground "Gold"      :bold t :weight bold))))
 '(Man-underline                              ((t (:foreground "LightBlue" :underline t))))
 '(Man-reverse                                ((t (:foreground "Black"     :background "Pink"))))

 '(man-bold                                   ((t (:bold t))))
 '(man-heading                                ((t (:bold t))))
 '(man-italic                                 ((t (:foreground "yellow"))))
 '(man-xref                                   ((t (:underline t))))

 '(dired-directory                            ((t (:foreground "Blue3" :bold t :weight bold))))
 '(dired-flagged                              ((t (:foreground "Red" :bold t :weight bold))))
 '(dired-header                               ((t (:inherit 'font-lock-type-face))))
 '(dired-ignored                              ((t (:inherit 'shadow))))
 '(dired-mark                                 ((t (:foreground "Purple" :bold t :weight bold))))
 '(dired-marked                               ((t (:foreground "Yellow" :bold t :weight bold))))
 '(dired-perm-write                           ((t (:inherit 'font-lock-comment-delimiter-face))))
 '(dired-symlink                              ((t (:foreground "Cyan"))))
 '(dired-warning                              ((t (:foreground "White" :background "Red"      :bold t :weight bold))))

 '(font-latex-sectioning-0-face               ((t (:foreground "Gold" :bold t :weight bold))))
 '(font-latex-sectioning-1-face               ((t (:foreground "Gold" :bold t :weight bold))))
 '(font-latex-sectioning-2-face               ((t (:foreground "Gold" :bold t :weight bold))))
 '(font-latex-sectioning-3-face               ((t (:foreground "Gold" :bold t :weight bold))))
 '(font-latex-sectioning-4-face               ((t (:foreground "Gold" :bold t :weight bold))))
 '(font-latex-sectioning-5-face               ((t (:foreground "Gold" :bold t :weight bold))))
 '(font-latex-slide-title-face                ((t (                   :bold t :weight bold :inherit 'font-lock-type-face))))

 '(linum                                      ((t (:inherit (shadow default) :foreground "deep pink"))))
)

(provide-theme 'mjr-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; mjr-dark-theme.el ends here
